name: WCA Vote Crawl

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz

      - name: Run crawler
        run: python wca_vote_crawler.py

      - name: Update WCA vote data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update WCA vote data"
          file_pattern: wca_votes.json
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"